### PR TITLE
Warn users when installing EOL .NET versions

### LINKED ISSUE #180: Add a warning message for installation of deprecated .NET versions
**Description:**
When installing a .NET version, we should check the `eol-date` field in `https://dotnetcli.blob.core.windows.net/dotnet/release-metadata/releases-index.json` (which we use to get latest .NET versions for wildcards) and provide an error message informing the user that the version they're installing is deprecated such as (suggestion):

> The current version of .NET being installed is deprecated and might not work correctly.

**Justification:**
The documentation was referencing .NET Core 2.2 which is deprecated and does not work on GitHub-hosted environments anymore (as reported in #176).
As there is no way to always ensure documentation won't reference unsupported versions of .NET without someone always updating the documentation, this could be a safeguard in the period between deprecation and documentation updates.

**Are you willing to submit a PR?**
Yes.

### PR DESCRIPTION
**Pull request by GGG-KILLER**
**Description:**
Implements a warning when users try to install an EOL version of .NET.

**Related issue:**
Closes #180

**Check list:**
- [ ] Mark if documentation changes are required.
- [ ] Mark if tests were added or updated to cover the changes.

### CODE REVIEW

**Review by vsafonkin — APPROVED** [review]

**Review by dmitry-shibanov — APPROVED** [review]

**Review by jetersen — APPROVED** [review]

**Review by MaksimZhukov — APPROVED** [review]

File: src/installer.ts [hunk 1]
```diff
@@ -283,7 +283,14 @@ export class DotnetCoreInstaller {
       );
     }
 
-    return releasesInfo[0]['releases.json'];
+    const releaseInfo = releasesInfo[0];
+    if (releaseInfo['support-phase'] === 'eol') {
+      core.warning(
+        `${releaseInfo['product']} ${releaseInfo['channel-version']} is no longer supported and may not work properly.`
```
Comment (MaksimZhukov) [inline src/installer.ts:289]:
```suggestion
        `${releaseInfo['product']} ${releaseInfo['channel-version']} is no longer supported and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the .NET support policy.`

```

**Comment by MaksimZhukov** [comment]
Hello @GGG-KILLER! Thank you for the contribution!
Could you please resolve a comment?

**Comment by GGG-KILLER** [comment]
> Hello @GGG-KILLER! Thank you for the contribution! Could you please resolve a comment?

Resolved!

File: src/installer.ts (hunk 1 above)
Comment (GGG-KILLER) [reply src/installer.ts]: Incorporated your change and am rebuilding `index.js`.

**Comment by GGG-KILLER** [comment]
> Hello @GGG-KILLER! Thank you for the contribution! Could you please resolve a comment?

Resolved!

File: src/installer.ts (hunk 1 above)
Comment (GGG-KILLER) [reply src/installer.ts]: Resolved

**Review by MaksimZhukov — APPROVED** [review]
